"""Requests 下载器。"""

from sd_webui_all_in_one.downloader.requests_downloader.api import download_file_from_url
from sd_webui_all_in_one.downloader.requests_downloader.models import (
    ARIA2_SIZE_OPTION_MAX,
    ARIA2_SIZE_OPTION_MIN,
    DEFAULT_MAX_CONNECTION_PER_SERVER,
    DEFAULT_MIN_SPLIT_SIZE,
    DEFAULT_PIECE_LENGTH,
    DEFAULT_SPLIT,
    DownloadCancelledError,
    DownloadConfigurationError,
    DownloadConnectTimeoutError,
    DownloadError,
    DownloadIntegrityError,
    DownloadLowSpeedError,
    DownloadPermanentHttpError,
    DownloadProgressEvent,
    DownloadReadTimeoutError,
    DownloadSizeIntegrityError,
    DownloadStateError,
    DownloadTransientError,
)

__all__ = [
    "ARIA2_SIZE_OPTION_MAX",
    "ARIA2_SIZE_OPTION_MIN",
    "DEFAULT_MAX_CONNECTION_PER_SERVER",
    "DEFAULT_MIN_SPLIT_SIZE",
    "DEFAULT_PIECE_LENGTH",
    "DEFAULT_SPLIT",
    "DownloadCancelledError",
    "DownloadConfigurationError",
    "DownloadConnectTimeoutError",
    "DownloadError",
    "DownloadIntegrityError",
    "DownloadLowSpeedError",
    "DownloadPermanentHttpError",
    "DownloadProgressEvent",
    "DownloadReadTimeoutError",
    "DownloadSizeIntegrityError",
    "DownloadStateError",
    "DownloadTransientError",
    "download_file_from_url",
]
