"""WebUI environment snapshot restore facade."""

from sd_webui_all_in_one.base_manager.snapshot_restore.extensions import (
    PACKAGE_KERNEL_WEBUI_TYPES,
    normalize_extension_name,
    restore_git_repository,
    restore_comfy_registry_extension,
    restore_extensions,
)
from sd_webui_all_in_one.base_manager.snapshot_restore.models import (
    logger,
    PackageRestoreAction,
    GitRestoreAction,
    RegistryRestoreAction,
    ExtensionCleanupAction,
    DiffStatus,
    RestoreOptionFlag,
    RestoreBlockerCode,
    RestoreBlockerScope,
    PACKAGE_DIFF_STATUS,
    GIT_DIFF_STATUS,
    REGISTRY_DIFF_STATUS,
    CHANGED_DIFF_STATUSES,
    DiffField,
    RestoreDiff,
    RestoreDiffCounts,
    RestoreDiffSummary,
    RestoreBlocker,
    SnapshotRestoreOptions,
    ExtensionRestoreTools,
    PackageRestorePlanItem,
    GitRestorePlanItem,
    ExtensionRestorePlanItem,
    SnapshotRestorePlan,
)
from sd_webui_all_in_one.base_manager.snapshot_restore.packages import (
    PYTORCH_PACKAGE_NAMES,
    PROTECTED_PACKAGE_NAMES,
    restore_python_packages,
)
from sd_webui_all_in_one.base_manager.snapshot_restore.service import (
    preview_webui_snapshot_restore,
    restore_webui_snapshot,
)

__all__ = [
    "PACKAGE_KERNEL_WEBUI_TYPES",
    "normalize_extension_name",
    "restore_git_repository",
    "restore_comfy_registry_extension",
    "restore_extensions",
    "logger",
    "PackageRestoreAction",
    "GitRestoreAction",
    "RegistryRestoreAction",
    "ExtensionCleanupAction",
    "DiffStatus",
    "RestoreOptionFlag",
    "RestoreBlockerCode",
    "RestoreBlockerScope",
    "PACKAGE_DIFF_STATUS",
    "GIT_DIFF_STATUS",
    "REGISTRY_DIFF_STATUS",
    "CHANGED_DIFF_STATUSES",
    "DiffField",
    "RestoreDiff",
    "RestoreDiffCounts",
    "RestoreDiffSummary",
    "RestoreBlocker",
    "SnapshotRestoreOptions",
    "ExtensionRestoreTools",
    "PackageRestorePlanItem",
    "GitRestorePlanItem",
    "ExtensionRestorePlanItem",
    "SnapshotRestorePlan",
    "PYTORCH_PACKAGE_NAMES",
    "PROTECTED_PACKAGE_NAMES",
    "restore_python_packages",
    "preview_webui_snapshot_restore",
    "restore_webui_snapshot",
]
