"""基础管理模块导出"""

from sd_webui_all_in_one.base_manager.base import (
    prepare_pytorch_install_info,
    install_pytorch_for_webui,
    reinstall_pytorch,
    clone_repo,
    pre_download_model_for_webui,
    launch_webui,
    get_repo_name_from_url,
    install_webui_model_from_library,
    apply_git_base_config_and_github_mirror,
    apply_hf_mirror,
)

from sd_webui_all_in_one.base_manager.comfyui_base import (
    ComfyUiCustomNodeInfo,
    ComfyUiLocalExtensionInfo,
    COMFYUI_REPO_URL,
    COMFYUI_CONFIG_PATH,
    install_comfyui,
    update_comfyui,
    check_comfyui_env,
    launch_comfyui,
    install_comfyui_custom_node,
    list_comfyui_custom_nodes,
    set_comfyui_custom_node_status,
    update_comfyui_custom_nodes,
    uninstall_comfyui_custom_node,
    install_comfyui_model_from_library,
    install_comfyui_model_from_url,
    list_comfyui_models,
    uninstall_comfyui_model,
)

from sd_webui_all_in_one.base_manager.fooocus_base import (
    FooocusBranchType,
    FooocusBranchInfo,
    FOOOCUS_PRESET_HF_PATH,
    FOOOCUS_PRESET_MS_PATH,
    FOOOCUS_TRANSLATE_ZH_PATH,
    FOOOCUS_BRANCH_LIST,
    display_fooocus_branch_list,
    install_fooocus_config,
    install_fooocus,
    switch_fooocus_branch,
    update_fooocus,
    check_fooocus_env,
    launch_fooocus,
    install_fooocus_model_from_library,
    install_fooocus_model_from_url,
    list_fooocus_models,
    uninstall_fooocus_model,
)

from sd_webui_all_in_one.base_manager.invokeai_base import (
    InvokeAILocalExtensionInfo,
    InvokeAILocalModelInfo,
    get_invokeai_require_torch_version,
    get_pytorch_mirror_type_for_ivnokeai,
    get_pytorch_for_invokeai,
    get_xformers_for_invokeai,
    sync_invokeai_component,
    install_invokeai_component,
    import_model_to_invokeai,
    install_pypatchmatch,
    run_invokeai,
    install_invokeai,
    update_invokeai,
    check_invokeai_env,
    launch_invokeai,
    install_invokeai_custom_nodes,
    set_invokeai_custom_nodes_status,
    list_invokeai_custom_nodes,
    update_invokeai_custom_nodes,
    uninstall_invokeai_custom_node,
    install_invokeai_model_from_library,
    install_invokeai_model_from_url,
    get_invokeai_model_list,
    list_invokeai_models,
    uninstall_model_from_invokeai,
    uninstall_invokeai_model,
    reinstall_invokeai_pytorch,
)

from sd_webui_all_in_one.base_manager.qwen_tts_webui_base import (
    QWEN_TTS_WEBUI_PRESET_HF_PATH,
    QWEN_TTS_WEBUI_PRESET_MS_PATH,
    QWEN_TTS_WEBUI_REPO,
    install_qwen_tts_webui_config,
    install_qwen_tts_webui,
    update_qwen_tts_webui,
    check_qwen_tts_webui_env,
    launch_qwen_tts_webui,
)

from sd_webui_all_in_one.base_manager.sd_scripts_base import (
    SDScriptsBranchType,
    SDScriptsBranchInfo,
    SD_SCRIPTS_BRANCH_LIST,
    display_sd_scripts_branch_list,
    export_requirements_from_toml_config,
    install_sd_scripts,
    switch_sd_scripts_branch,
    update_sd_scripts,
    check_sd_scripts_env,
    install_sd_scripts_model_from_library,
    install_sd_scripts_model_from_url,
    list_sd_scripts_models,
    uninstall_sd_scripts_model,
)

from sd_webui_all_in_one.base_manager.sd_trainer_base import (
    SDTrainerBranchType,
    SDTrainerBranchInfo,
    SD_TRAINER_BRANCH_LIST,
    display_sd_trainer_branch_list,
    install_sd_trainer,
    switch_sd_trainer_branch,
    update_sd_trainer,
    check_sd_trainer_env,
    launch_sd_trainer,
    install_sd_trainer_model_from_library,
    install_sd_trainer_model_from_url,
    list_sd_trainer_models,
    uninstall_sd_trainer_model,
)

from sd_webui_all_in_one.base_manager.sd_webui_base import (
    SDWebUiBranchType,
    SDWebUiBranchInfo,
    SDWebUiExtensionInfo,
    SDWebUiLocalExtensionInfo,
    SD_WEBUI_CONFIG_PATH,
    SD_WEBUI_BRANCH_LIST,
    display_sd_webui_branch_list,
    install_sd_webui_config,
    install_clip_package,
    install_sd_webui,
    switch_sd_webui_branch,
    update_sd_webui,
    check_sd_webui_env,
    set_sd_webui_extension_download_list_mirror,
    launch_sd_webui,
    install_sd_webui_extension,
    set_sd_webui_extensions_status,
    list_sd_webui_extensions,
    update_sd_webui_extensions,
    uninstall_sd_webui_extension,
    install_sd_webui_model_from_library,
    install_sd_webui_model_from_url,
    list_sd_webui_models,
    uninstall_sd_webui_model,
)

# 导出的公共 API 列表，按模块分类
__all__ = [
    # base.py - 基础功能模块
    "prepare_pytorch_install_info",
    "install_pytorch_for_webui",
    "reinstall_pytorch",
    "clone_repo",
    "pre_download_model_for_webui",
    "launch_webui",
    "get_repo_name_from_url",
    "install_webui_model_from_library",
    "apply_git_base_config_and_github_mirror",
    "apply_hf_mirror",
    # comfyui_base.py - ComfyUI 管理模块
    # 类型定义
    "ComfyUiCustomNodeInfo",
    "ComfyUiLocalExtensionInfo",
    # 常量
    "COMFYUI_REPO_URL",
    "COMFYUI_CONFIG_PATH",
    # 函数
    "install_comfyui",
    "update_comfyui",
    "check_comfyui_env",
    "launch_comfyui",
    "install_comfyui_custom_node",
    "list_comfyui_custom_nodes",
    "set_comfyui_custom_node_status",
    "update_comfyui_custom_nodes",
    "uninstall_comfyui_custom_node",
    "install_comfyui_model_from_library",
    "install_comfyui_model_from_url",
    "list_comfyui_models",
    "uninstall_comfyui_model",
    # fooocus_base.py - Fooocus 管理模块
    # 类型定义
    "FooocusBranchType",
    "FooocusBranchInfo",
    # 常量
    "FOOOCUS_PRESET_HF_PATH",
    "FOOOCUS_PRESET_MS_PATH",
    "FOOOCUS_TRANSLATE_ZH_PATH",
    "FOOOCUS_BRANCH_LIST",
    # 函数
    "display_fooocus_branch_list",
    "install_fooocus_config",
    "install_fooocus",
    "switch_fooocus_branch",
    "update_fooocus",
    "check_fooocus_env",
    "launch_fooocus",
    "install_fooocus_model_from_library",
    "install_fooocus_model_from_url",
    "list_fooocus_models",
    "uninstall_fooocus_model",
    # invokeai_base.py - InvokeAI 管理模块
    # 类型定义
    "InvokeAILocalExtensionInfo",
    "InvokeAILocalModelInfo",
    # 函数
    "get_invokeai_require_torch_version",
    "get_pytorch_mirror_type_for_ivnokeai",
    "get_pytorch_for_invokeai",
    "get_xformers_for_invokeai",
    "sync_invokeai_component",
    "install_invokeai_component",
    "import_model_to_invokeai",
    "install_pypatchmatch",
    "run_invokeai",
    "install_invokeai",
    "update_invokeai",
    "check_invokeai_env",
    "launch_invokeai",
    "install_invokeai_custom_nodes",
    "set_invokeai_custom_nodes_status",
    "list_invokeai_custom_nodes",
    "update_invokeai_custom_nodes",
    "uninstall_invokeai_custom_node",
    "install_invokeai_model_from_library",
    "install_invokeai_model_from_url",
    "get_invokeai_model_list",
    "list_invokeai_models",
    "uninstall_model_from_invokeai",
    "uninstall_invokeai_model",
    "reinstall_invokeai_pytorch",
    # qwen_tts_webui_base.py - Qwen TTS WebUI 管理模块
    # 常量
    "QWEN_TTS_WEBUI_PRESET_HF_PATH",
    "QWEN_TTS_WEBUI_PRESET_MS_PATH",
    "QWEN_TTS_WEBUI_REPO",
    # 函数
    "install_qwen_tts_webui_config",
    "install_qwen_tts_webui",
    "update_qwen_tts_webui",
    "check_qwen_tts_webui_env",
    "launch_qwen_tts_webui",
    # sd_scripts_base.py - SD Scripts 管理模块
    # 类型定义
    "SDScriptsBranchType",
    "SDScriptsBranchInfo",
    # 常量
    "SD_SCRIPTS_BRANCH_LIST",
    # 函数
    "display_sd_scripts_branch_list",
    "export_requirements_from_toml_config",
    "install_sd_scripts",
    "switch_sd_scripts_branch",
    "update_sd_scripts",
    "check_sd_scripts_env",
    "install_sd_scripts_model_from_library",
    "install_sd_scripts_model_from_url",
    "list_sd_scripts_models",
    "uninstall_sd_scripts_model",
    # sd_trainer_base.py - SD Trainer 管理模块
    # 类型定义
    "SDTrainerBranchType",
    "SDTrainerBranchInfo",
    # 常量
    "SD_TRAINER_BRANCH_LIST",
    # 函数
    "display_sd_trainer_branch_list",
    "install_sd_trainer",
    "switch_sd_trainer_branch",
    "update_sd_trainer",
    "check_sd_trainer_env",
    "launch_sd_trainer",
    "install_sd_trainer_model_from_library",
    "install_sd_trainer_model_from_url",
    "list_sd_trainer_models",
    "uninstall_sd_trainer_model",
    # sd_webui_base.py - SD WebUI 管理模块
    # 类型定义
    "SDWebUiBranchType",
    "SDWebUiBranchInfo",
    "SDWebUiExtensionInfo",
    "SDWebUiLocalExtensionInfo",
    # 常量
    "SD_WEBUI_CONFIG_PATH",
    "SD_WEBUI_BRANCH_LIST",
    # 函数
    "display_sd_webui_branch_list",
    "install_sd_webui_config",
    "install_clip_package",
    "install_sd_webui",
    "switch_sd_webui_branch",
    "update_sd_webui",
    "check_sd_webui_env",
    "set_sd_webui_extension_download_list_mirror",
    "launch_sd_webui",
    "install_sd_webui_extension",
    "set_sd_webui_extensions_status",
    "list_sd_webui_extensions",
    "update_sd_webui_extensions",
    "uninstall_sd_webui_extension",
    "install_sd_webui_model_from_library",
    "install_sd_webui_model_from_url",
    "list_sd_webui_models",
    "uninstall_sd_webui_model",
]
