def install_sd_trainer() -> None: ...


def check_sd_trainer_env() -> None: ...


def launch_sd_trainer() -> None: ...


def install_model_from_library() -> None: ...


def install_model_from_url() -> None: ...


def list_models() -> None: ...


def uninstall_model() -> None: ...
