"""WebUI environment snapshots.

The package facade preserves the former ``base_manager.snapshot`` public API;
implementation details are grouped by responsibility in sibling modules.
"""

from sd_webui_all_in_one.base_manager.snapshot.codec import (
    snapshot_from_dict,
)
from sd_webui_all_in_one.base_manager.snapshot.collection import (
    collect_python_info,
    collect_system_info,
    collect_installed_packages,
    repository_state_to_snapshot,
    repository_dirty,
    collect_repository_snapshot,
    collect_git_extensions,
    build_webui_snapshot,
)
from sd_webui_all_in_one.base_manager.snapshot.io import (
    load_snapshot,
    comfyui_manager_snapshot_from_dict,
)
from sd_webui_all_in_one.base_manager.snapshot.models import (
    SNAPSHOT_SCHEMA_VERSION,
    logger,
    JsonPrimitive,
    JsonValue,
    JsonObject,
    SourceType,
    ExtensionSourceType,
    ExtensionEnabledResolver,
    default_system_snapshot,
    DirectUrlVcsInfo,
    DirectUrlDirInfo,
    DirectUrlArchiveInfo,
    DirectUrlSnapshot,
    WheelSnapshot,
    PackageSnapshot,
    PythonSnapshot,
    SystemSnapshot,
    RepositorySnapshot,
    ExtensionSnapshot,
    WebUiIdentitySnapshot,
    WebUiSnapshot,
    SnapshotSummary,
    SavedSnapshot,
    utc_now_iso,
    snapshot_to_dict,
    json_safe,
)
from sd_webui_all_in_one.base_manager.snapshot.storage import (
    save_snapshot,
    default_snapshot_output,
    resolve_snapshot_output,
    list_webui_snapshots,
    create_webui_snapshot,
    delete_snapshot,
)

__all__ = [
    "snapshot_from_dict",
    "collect_python_info",
    "collect_system_info",
    "collect_installed_packages",
    "repository_state_to_snapshot",
    "repository_dirty",
    "collect_repository_snapshot",
    "collect_git_extensions",
    "build_webui_snapshot",
    "load_snapshot",
    "comfyui_manager_snapshot_from_dict",
    "SNAPSHOT_SCHEMA_VERSION",
    "logger",
    "JsonPrimitive",
    "JsonValue",
    "JsonObject",
    "SourceType",
    "ExtensionSourceType",
    "ExtensionEnabledResolver",
    "default_system_snapshot",
    "DirectUrlVcsInfo",
    "DirectUrlDirInfo",
    "DirectUrlArchiveInfo",
    "DirectUrlSnapshot",
    "WheelSnapshot",
    "PackageSnapshot",
    "PythonSnapshot",
    "SystemSnapshot",
    "RepositorySnapshot",
    "ExtensionSnapshot",
    "WebUiIdentitySnapshot",
    "WebUiSnapshot",
    "SnapshotSummary",
    "SavedSnapshot",
    "utc_now_iso",
    "snapshot_to_dict",
    "json_safe",
    "save_snapshot",
    "default_snapshot_output",
    "resolve_snapshot_output",
    "list_webui_snapshots",
    "create_webui_snapshot",
    "delete_snapshot",
]
