"""Hotpatcher configuration and runtime host facade."""

from sd_webui_all_in_one.base_manager.hotpatcher_manager.config import (
    logger,
    HOTPATCHER_PATH,
    DEFAULT_HOTPATCHER_CONFIG_PATH,
    DEFAULT_RUNTIME_HOST,
    DEFAULT_RUNTIME_PORT,
    HOTPATCHER_ENV_PREFIX,
    ensure_hotpatcher_import_path,
    get_hotpatcher_default_config,
    get_hotpatcher_catalog,
    normalize_hotpatcher_config,
    load_hotpatcher_config,
    save_hotpatcher_config,
    export_hotpatcher_default_config,
    apply_hotpatcher_config,
    apply_hotpatcher_launch_env,
    configure_hotpatcher_for_current_process,
    remove_hotpatcher_launch_env,
    ensure_hotpatcher_pythonpath_first,
    build_hotpatcher_runtime_env,
    launch_hotpatcher_manager_gui,
)
from sd_webui_all_in_one.base_manager.hotpatcher_manager.host import (
    HotpatcherRuntimeHost,
    wait_for_runtime_log,
    wait_for_service_channel,
)
from sd_webui_all_in_one.base_manager.hotpatcher_manager.protocol import (
    RuntimeLogEntry,
    RuntimeMessage,
    RuntimeBrowserEvent,
    RemoteServiceError,
    RuntimeServiceChannel,
)

__all__ = [
    "logger",
    "HOTPATCHER_PATH",
    "DEFAULT_HOTPATCHER_CONFIG_PATH",
    "DEFAULT_RUNTIME_HOST",
    "DEFAULT_RUNTIME_PORT",
    "HOTPATCHER_ENV_PREFIX",
    "ensure_hotpatcher_import_path",
    "get_hotpatcher_default_config",
    "get_hotpatcher_catalog",
    "normalize_hotpatcher_config",
    "load_hotpatcher_config",
    "save_hotpatcher_config",
    "export_hotpatcher_default_config",
    "apply_hotpatcher_config",
    "apply_hotpatcher_launch_env",
    "configure_hotpatcher_for_current_process",
    "remove_hotpatcher_launch_env",
    "ensure_hotpatcher_pythonpath_first",
    "build_hotpatcher_runtime_env",
    "launch_hotpatcher_manager_gui",
    "HotpatcherRuntimeHost",
    "wait_for_runtime_log",
    "wait_for_service_channel",
    "RuntimeLogEntry",
    "RuntimeMessage",
    "RuntimeBrowserEvent",
    "RemoteServiceError",
    "RuntimeServiceChannel",
]
