###############################
# SD WebUI All In One Aria2 配置文件
#
# 参考: https://aria2.github.io/manual/en/html/aria2c.html
#
###############################


################ RPC ################
# 启用 JSON-RPC/XML-RPC 服务器.
enable-rpc=true
# 在 RPC 响应中添加值为 * 的 Access-Control-Allow-Origin 头字段.
rpc-allow-origin-all=true
# 在所有网络接口上监听传入的 JSON-RPC/XML-RPC 请求.
rpc-listen-all=false


################ 文件系统 ################
# 每隔 SEC 秒保存一次控制文件(*.aria2).
auto-save-interval=10
# 启用磁盘缓存.
disk-cache=64M
# 指定文件分配方法.
file-allocation=trunc
# 对于大小小于 SIZE 的文件不进行文件分配
no-file-allocation-limit=64M
# 每隔 SEC 秒将错误/未完成的下载保存到 --save-session 选项指定的文件中.
save-session-interval=10


################ 任务 ################
# 最大同时下载任务数
max-concurrent-downloads=16
# 每个服务器的最大连接数
max-connection-per-server=16
# 单个文件的最大分段数
split=16
# 在计算并发活动下载数时排除仅做种的下载
bt-detach-seed-only=true
# 使用 --ca-certificate 选项中指定的证书验证对等方.
check-certificate=false
# 如果 aria2 从远程 HTTP/FTP 服务器收到 NUM 次"文件未找到"状态
# 而没有获得单个字节, 则强制下载失败.
max-file-not-found=10
# 设置尝试次数.
max-tries=0
# 设置重试之间等待的秒数.当 SEC > 0 时, 如果 HTTP 服务器返回 503 响应, aria2 将重试下载.
retry-wait=10
# 设置建立到 HTTP/FTP/代理服务器连接的连接超时(秒). 建立连接后, 此选项不再生效, 改用 --timeout 选项.
connect-timeout=10
# 设置超时时间(秒).
timeout=10
# aria2 不会分割小于 2*SIZE 字节范围.
min-split-size=1M
# 发送 Accept: deflate,  gzip 请求头.
http-accept-gzip=true
# 从远程 HTTP/FTP 服务器检索远程文件的时间戳, 如果可用, 则将其应用于本地文件.
remote-time=true
# 设置输出下载进度摘要的间隔(秒).设置为 0 将禁止输出.
summary-interval=0
# 将 Content-Disposition 头中的引号字符串处理为 UTF-8 而不是 ISO-8859-1, 例如 filename 参数, 但不包括扩展版本 filename*.
content-disposition-default-utf8=true



################ BT 任务 ################
# 启用本地对等点发现.
bt-enable-lpd=true
# 要求使用 arc4 加密 BitTorrent 消息有效负载.
# bt-force-encryption=true
# 如果设置为 true, 在使用 --check-integrity 选项进行哈希检查后, 如果文件完整, 则继续做种文件.
bt-hash-check-seed=true
# 将磁力链接元数据保存为 .torrent 文件以便快速恢复会话.
bt-save-metadata=true
# 重启时加载缓存的 .torrent 文件, 而不是从 DHT 重新下载.
bt-load-saved-metadata=true
# 指定每个种子的最大对等点数.
bt-max-peers=128
# 尝试首先下载每个文件的第一块和最后一块.这对于预览文件很有用.
bt-prioritize-piece=head
# 在 BitTorrent 下载完成时删除未选择的文件.
bt-remove-unselected-file=true
# 在不验证分块哈希的情况下做种先前下载的文件.
# 恢复会话时需要立即做种(与 force-save=true 配对).
# 如果没有此选项, aria2 会在重启时对所有分块进行哈希检查, 从而延迟做种开始.
bt-seed-unverified=true
# 设置建立到 tracker 连接的连接超时(秒).建立连接后, 此选项不再生效, 改用 --bt-tracker-timeout 选项.
bt-tracker-connect-timeout=10
# 设置超时时间(秒).
bt-tracker-timeout=10
# 设置主机和端口作为 IPv4 DHT 网络的入口点.
dht-entry-point=dht.transmissionbt.com:6881
# 设置主机和端口作为 IPv6 DHT 网络的入口点.
dht-entry-point6=dht.transmissionbt.com:6881
# 启用 IPv4 DHT 功能. 它还启用 UDP tracker 支持.
enable-dht=true
# 启用 IPv6 DHT 功能.
enable-dht6=true
# 启用对等点交换扩展.
enable-peer-exchange=true
# 指定在 bittorrent 扩展握手期间用于对等方客户端版本的字符串.
peer-agent=Transmission/3.00
# 指定对等点 ID 的前缀.
peer-id-prefix=-TR3000-
