name: Build Musubi Tuner

on:

  workflow_dispatch:

jobs:
  Build-Musubi-Tuner:
    name: Build Musubi Tuner
    runs-on: windows-latest
    env:
      PYTHONIOENCODING: utf-8
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup portable build
        uses: ./.github/actions/setup-portable-build

      - name: Launch SD-Trainer-Script Installer
        env:
          SD_WEBUI_ALL_IN_ONE_SKIP_TORCH_DEVICE_COMPATIBILITY: 1
        shell: pwsh
        run: |
          & "${{ github.workspace }}/installer/sd_trainer_script_installer.ps1" `
            -InstallPath "${{ github.workspace }}/musubi_tuner" `
            -PyTorchMirrorType cu130 `
            -BuildMode `
            -BuildWithLaunch `
            -InstallBranch "musubi_tuner_main" `
            -DisableAutoMirror `
            -DisablePyPIMirror `
            -DisableGithubMirror `
            -DisableHuggingFaceMirror `
            -NoPreDownloadModel

      - name: Finalize portable package
        uses: ./.github/actions/finalize-portable
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          MODELSCOPE_API_TOKEN: ${{ secrets.MODELSCOPE_API_TOKEN }}
        with:
          install-path: ${{ github.workspace }}/musubi_tuner
          software-name: musubi_tuner
          upload-path: ${{ github.workspace }}/sdnote
          hf-repo-id: licyk/sdnote
          ms-repo-id: licyks/sdnote
