name: Check Installer Version

on:
  push:
    paths:
      - '**.ps1'
      - '.github/check_installer_version.ps1'
      - 'sd_webui_all_in_one/version.py'
      - '.github/workflows/check_version.yaml'
  delete:
  create:
  workflow_dispatch:

jobs:
  Check-Installer-Version:
    name: Check Installer Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Check Installer Version
        shell: pwsh
        run: |
          & "${{ github.workspace }}/.github/check_installer_version.ps1" -Workspace "${{ github.workspace }}"
