name: PSScript Lint

on:
  push:
    paths:
      - '**.ps1'
      - '**.psm1'
      - '**.psd1'
      - '.github/check_installer_param_config.py'
      - '.github/pwsh_lint.ps1'
      - '.github/workflows/pwsh-lint.yml'
  delete:
  create:
  workflow_dispatch:

jobs:
  lint-with-PSScriptAnalyzer:
    name: PSScript Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install PSScriptAnalyzer module
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer -ErrorAction Stop

      - name: Run PowerShell lint tooling
        shell: pwsh
        run: |
          & "${{ github.workspace }}/.github/pwsh_lint.ps1" -Workspace "${{ github.workspace }}"
