name: Update Portable Release Note

on:
  schedule:
  # * is a special character in YAML so you have to quote this string
  # UTC 17:00 -> CST (China) 1:00, see https://datetime360.com/cn/utc-cst-china-time/
  # https://docs.github.com/zh/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule
  - cron: '20 22 * * *'
  workflow_dispatch:

jobs:
  Update-Portable-Release-Note:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Update Portable Release Note
        shell: bash
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PIP_BREAK_SYSTEM_PACKAGES: 1
          PIP_DISABLE_PIP_VERSION_CHECK: 1
          PIP_NO_WARN_SCRIPT_LOCATION: 0
          PYTHONUTF8: 1
          PYTHONIOENCODING: utf-8
        run: |
          pip install requests
          python "${{ github.workspace }}/.github/update_portable_release_note.py"
